"""Database compatibility layer for the PostgreSQL production backend.

The application historically used SQLite directly.  This module exposes the
small DB-API surface used by server.py while making PostgreSQL the only live
database whenever DATABASE_URL is configured.
"""
from __future__ import annotations

import re
import os
import threading
from collections.abc import Iterator, Mapping
from pathlib import Path
from typing import Any

import psycopg
from psycopg import sql
from psycopg.errors import IntegrityError
try:
    from psycopg_pool import ConnectionPool
except ImportError:  # Allows source-only checks; live connections fail closed below.
    ConnectionPool = None


DATABASE_URL = ""
_POOL: Any | None = None
_POOL_LOCK = threading.Lock()


def _bounded_int_env(name: str, default: int, minimum: int, maximum: int) -> int:
    try:
        value = int(os.environ.get(name, str(default)))
    except (TypeError, ValueError):
        return default
    return max(minimum, min(maximum, value))


def _pool() -> Any:
    global _POOL
    if not DATABASE_URL:
        raise RuntimeError("DATABASE_URL não configurada. O PostgreSQL é obrigatório.")
    if ConnectionPool is None:
        raise RuntimeError("psycopg_pool não instalado. Instale as dependências antes de iniciar o CRM.")
    if _POOL is None:
        with _POOL_LOCK:
            if _POOL is None:
                minimum = _bounded_int_env("DB_POOL_MIN", 2, 1, 20)
                maximum = _bounded_int_env("DB_POOL_MAX", 12, minimum, 60)
                timeout = _bounded_int_env("DB_POOL_TIMEOUT_SECONDS", 8, 1, 60)
                _POOL = ConnectionPool(
                    DATABASE_URL,
                    min_size=minimum,
                    max_size=maximum,
                    timeout=timeout,
                    max_idle=300,
                    max_lifetime=1800,
                    check=ConnectionPool.check_connection,
                    open=True,
                    name="iea-crm",
                )
    return _POOL


def pool_stats() -> dict[str, int]:
    return _pool().get_stats()


def configure(database_url: str) -> None:
    global DATABASE_URL, _POOL
    configured_url = (database_url or "").strip()
    with _POOL_LOCK:
        if _POOL is not None and configured_url != DATABASE_URL:
            _POOL.close()
            _POOL = None
        DATABASE_URL = configured_url


def using_postgres() -> bool:
    return bool(DATABASE_URL)


class DbRow(Mapping):
    """Row supporting SQLite-style numeric and named access plus dict(row)."""

    def __init__(self, columns: list[str], values: tuple[Any, ...]):
        self._columns = columns
        self._values = values
        self._mapping = dict(zip(columns, values))

    def __getitem__(self, key):
        if isinstance(key, int):
            return self._values[key]
        return self._mapping[key]

    def __iter__(self) -> Iterator[str]:
        return iter(self._columns)

    def __len__(self) -> int:
        return len(self._columns)

    def keys(self):
        return self._mapping.keys()


def _replace_qmarks(query: str) -> str:
    """Convert SQLite placeholders without touching quoted string literals."""
    out: list[str] = []
    quote: str | None = None
    index = 0
    while index < len(query):
        char = query[index]
        if quote:
            out.append(char)
            if char == quote:
                if index + 1 < len(query) and query[index + 1] == quote:
                    out.append(query[index + 1])
                    index += 1
                else:
                    quote = None
        elif char in {"'", '"'}:
            quote = char
            out.append(char)
        elif char == "?":
            out.append("%s")
        else:
            out.append(char)
        index += 1
    return "".join(out)


def translate_query(query: str) -> str:
    # psycopg uses percent signs for client-side placeholders even when the
    # statement only contains SQLite-style question marks. Escape every
    # percent already present in legacy SQL (strftime formats and LIKE
    # patterns) before generating the real ``%s`` placeholders below.
    translated = query.replace("%", "%%")
    translated = re.sub(
        r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        translated,
        flags=re.I,
    )
    translated = re.sub(
        r"DEFAULT\s+CURRENT_TIMESTAMP",
        "DEFAULT (to_char(CURRENT_TIMESTAMP AT TIME ZONE 'America/Cuiaba', 'YYYY-MM-DD HH24:MI:SS'))",
        translated,
        flags=re.I,
    )
    translated = re.sub(r"\bINSERT\s+OR\s+IGNORE\s+INTO\b", "INSERT INTO", translated, flags=re.I)
    was_ignore = bool(re.search(r"\bINSERT\s+OR\s+IGNORE\s+INTO\b", query, flags=re.I))
    translated = re.sub(r"\bINSTR\s*\(", "strpos(", translated, flags=re.I)
    translated = re.sub(r"\bCOLLATE\s+NOCASE\b", 'COLLATE "nocase"', translated, flags=re.I)
    translated = re.sub(r"\bMAX\s*\(\s*0\s*,", "GREATEST(0,", translated, flags=re.I)
    if was_ignore and not re.search(r"\bON\s+CONFLICT\b", translated, flags=re.I):
        returning = re.search(r"\bRETURNING\b", translated, flags=re.I)
        if returning:
            translated = translated[: returning.start()] + " ON CONFLICT DO NOTHING " + translated[returning.start() :]
        else:
            translated = translated.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"
    return _replace_qmarks(translated)


class DbCursor:
    def __init__(self, cursor):
        self._cursor = cursor
        self._lastrowid = None

    @property
    def rowcount(self) -> int:
        return self._cursor.rowcount

    @property
    def lastrowid(self):
        return self._lastrowid

    @lastrowid.setter
    def lastrowid(self, value):
        self._lastrowid = value

    def _row(self, values):
        if values is None:
            return None
        columns = [item.name for item in self._cursor.description]
        return DbRow(columns, tuple(values))

    def fetchone(self):
        return self._row(self._cursor.fetchone())

    def __iter__(self):
        # sqlite3.Cursor is directly iterable ("for row in db.execute(...)"),
        # a pattern used throughout this codebase. Support it here too so the
        # PostgreSQL backend stays a drop-in replacement.
        return iter(self.fetchall())

    def fetchall(self):
        rows = self._cursor.fetchall()
        if not rows:
            return []
        columns = [item.name for item in self._cursor.description]
        return [DbRow(columns, tuple(row)) for row in rows]


class PostgresConnection:
    backend = "postgres"

    def __init__(self):
        if not DATABASE_URL:
            raise RuntimeError("DATABASE_URL não configurada. O PostgreSQL é obrigatório.")
        self._pool = _pool()
        self._connection = self._pool.getconn()
        self._closed = False

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, traceback):
        if exc_type is None:
            self.commit()
        else:
            self.rollback()
        self.close()

    def close(self):
        if self._closed:
            return
        self._closed = True
        self._pool.putconn(self._connection)

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def _table_info(self, table_name: str) -> DbCursor:
        cursor = self._connection.cursor()
        cursor.execute(
            """
            SELECT ordinal_position - 1 AS cid, column_name AS name,
                   data_type AS type, CASE WHEN is_nullable='NO' THEN 1 ELSE 0 END AS notnull,
                   column_default AS dflt_value, 0 AS pk
              FROM information_schema.columns
             WHERE table_schema='public' AND table_name=%s
             ORDER BY ordinal_position
            """,
            (table_name,),
        )
        return DbCursor(cursor)

    def execute(self, query: str, parameters=()) -> DbCursor:
        stripped = query.strip()
        pragma_table = re.match(r"PRAGMA\s+table_info\(([^)]+)\)", stripped, flags=re.I)
        if pragma_table:
            return self._table_info(pragma_table.group(1).strip("'\" "))
        if re.match(r"PRAGMA\s+", stripped, flags=re.I):
            cursor = self._connection.cursor()
            cursor.execute("SELECT 1 WHERE FALSE")
            return DbCursor(cursor)
        if re.search(r"FROM\s+sqlite_master", query, flags=re.I):
            cursor = self._connection.cursor()
            # The only remaining sqlite_master probe checks whether the legacy
            # users-table role constraint already contains the ASB role.  The
            # PostgreSQL schema is created with that role, so expose an
            # equivalent definition and prevent the destructive SQLite table
            # rebuild path from running against a relational PostgreSQL graph.
            cursor.execute(
                "SELECT %s AS sql",
                ("CHECK(access_role IN ('owner','professional','admin','crc','asb'))",),
            )
            return DbCursor(cursor)

        cursor = self._connection.cursor()
        control = self._connection.cursor()
        translated = translate_query(query)
        control.execute("SAVEPOINT iea_statement")
        try:
            cursor.execute(translated, parameters or ())
            wrapped = DbCursor(cursor)
            if re.match(r"\s*INSERT\s+", translated, flags=re.I) and "RETURNING" not in translated.upper():
                control.execute("SAVEPOINT iea_lastval")
                sequence_cursor = self._connection.cursor()
                try:
                    sequence_cursor.execute("SELECT LASTVAL()")
                    wrapped.lastrowid = sequence_cursor.fetchone()[0]
                    control.execute("RELEASE SAVEPOINT iea_lastval")
                except psycopg.Error:
                    control.execute("ROLLBACK TO SAVEPOINT iea_lastval")
                    control.execute("RELEASE SAVEPOINT iea_lastval")
                finally:
                    sequence_cursor.close()
            control.execute("RELEASE SAVEPOINT iea_statement")
        except psycopg.Error:
            control.execute("ROLLBACK TO SAVEPOINT iea_statement")
            control.execute("RELEASE SAVEPOINT iea_statement")
            raise
        finally:
            control.close()
        return wrapped

    def executemany(self, query: str, sequence) -> DbCursor:
        cursor = self._connection.cursor()
        control = self._connection.cursor()
        control.execute("SAVEPOINT iea_statement")
        try:
            cursor.executemany(translate_query(query), sequence)
            control.execute("RELEASE SAVEPOINT iea_statement")
        except psycopg.Error:
            control.execute("ROLLBACK TO SAVEPOINT iea_statement")
            control.execute("RELEASE SAVEPOINT iea_statement")
            raise
        finally:
            control.close()
        return DbCursor(cursor)

    def executescript(self, schema_text: str) -> None:
        compatibility = (Path(__file__).resolve().parent / "postgres_compat.sql").read_text(encoding="utf-8")
        converted = compatibility + "\n" + convert_schema(schema_text)
        cursor = self._connection.cursor()
        cursor.execute(converted)
        cursor.close()


def convert_schema(schema_text: str) -> str:
    result = schema_text
    result = re.sub(
        r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        result,
        flags=re.I,
    )
    result = re.sub(r"\bBLOB\b", "BYTEA", result, flags=re.I)
    result = re.sub(
        r"DEFAULT\s+CURRENT_TIMESTAMP",
        "DEFAULT (to_char(CURRENT_TIMESTAMP AT TIME ZONE 'America/Cuiaba', 'YYYY-MM-DD HH24:MI:SS'))",
        result,
        flags=re.I,
    )
    result = re.sub(r"\bCOLLATE\s+NOCASE\b", 'COLLATE "nocase"', result, flags=re.I)
    return result


def connect() -> PostgresConnection:
    return PostgresConnection()
